# General
general:
  test_id: "base"
  uda: True

# Model parameters.
model:
  model_name: "unet"
  constraint_name: "multitask_strategy"
  mt_time: False
  pooling: False
  after_encoder: False
  weight: 1
  dropout:
  # use_geo: True
  # use_time: False
  # use_domains: False
  # use_coords_pos_enc: True
  # use_label_distr: False
  num_classes: 13
  num_channels: 3
  class_ignored: 0
  ckpt_path: False

# Metadata for spatiotemporal info.
metadata:
  pos_enc_coords: True
  circle_encoding: True
  encoding_freq: 10000
  geo_noise: 30000

# Optimization parameters.
optim:
  optim_type: "adamw"
  num_epochs: 120
  lr: 0.0003
  beta: [0.9, 0.999]
  end_lr: 0.000005
  weight_decay: 0.001
  lr_schedule_type: "step_lr"
  step: 120
  gamma: 0.75
  patience: 40

# Data parameters:
data:
  bands: 'rgb' #rgb rgbir rgbirh
  path: '../data/'
  train:
    img_txt: '../data/sub_train_imgs.txt'
    mask_txt: '../data/sub_train_masks.txt'
    batch_size: 25
    transform: "randaugment" #no yes randaugment
    normalization: [[0.44627694, 0.46320033, 0.42865627], 
                      [0.2055539 , 0.18050476, 0.177541]]
  val:
    img_txt: '../data/sub_test_imgs.txt'
    mask_txt: '../data/sub_test_masks.txt'
    normalization: [[0.44609856, 0.46605311, 0.43317396], 
                      [0.21038504, 0.18305449, 0.17746451]]
  test:
    cropsize: 512
    img_txt: '../data/sub_test_imgs.txt'
    mask_txt: '../data/sub_test_masks.txt'
    plot_results: True
    net: "unet"
    crf: False